### ISSUE TITLE
몬티 홀 문제(1회)의 결과 반환 함수

### ISSUE THREAD

**Issue by 1jeongg** [team-BEBEBE/Monty-Hall-problem-team#1]
## 몬티 홀(1회)의 결과 반환 함수

참가자가 차가 있는 문을 열었는지에 대한 결과값을 반환합니다.

- [x] 차 선택
- [x] 첫 번째 선택
- [x] 첫 번째 문 열기
- [x] 두 번째 문 열기
- [x] 차가 있는 문을 열었는지를 반환

**Comment by ChoMinGi** [comment]
기능 구현에 쓰셨던 래퍼런스 써주시면 좋을것 같습니다!
